name: Executive Traveller
favicon: null
layout_spectrum: 0.8010212809313089
typography_spectrum: 0.2632459544111043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#f9bb24'
    - '#ed202b'
    - '#c09123'
    - '#822026'
  brandStrength: 0.5
  lightness: 0.182234569452703
  saturation: 0.5782215150538832
  rhythmicContrast: 0.2945744516327977
purpose: []
